### PR TITLE
Port to react 16, enzyme 3

### PR DESCRIPTION
**Pull request by bruce-binary**
* fixed remaining broken unit tests
* upgrade storybook

### CODE REVIEW

**Comment by bruce-binary** [comment]
owh shit. Lemme have a look at what caused that fail

**Comment by bruce-binary** [comment]
@aminroosta these are flow errors. Should I fix them? A little surprised these errors never came up before

**Comment by aminroosta** [comment]
@brucebinary Take a look at [travis.yml](https://github.com/binary-com/binary-components/blob/master/.travis.yml), we are installing flow-bin@0.52.0.

It's very likely that another version will fix the travis errors, cause these are all caused by recent flow language breaking changes.

**Comment by bruce-binary** [comment]
I don't understand how all these flow errors came out after porting to react 16 when very little of the existing codebase changed. It's as if the flow checker was only recently enabled.

**Comment by bruce-binary** [comment]
@aminroosta aite I'll take a look

**Comment by bruce-binary** [comment]
I also noticed that the flow check does not apply to binary next-gen. Why only binary-components?

**Comment by bruce-binary** [comment]
@aminroosta ok upgrading it spawn a ton more errors.

**Comment by bruce-binary** [comment]
but at least now the errors are consistent to what I have locally

**Comment by bruce-binary** [comment]
@aminroosta I disagree that the code should to be ported to be latest flow standard. 

1. The code here already works fine in binary next-gen. Porting the code doesn't add any features; it just adds type checking, and should not be considered a priority until the new version of next-gen releases.
2. The porting will take some time. We are talking about the *entire* code base, not a few files. There were about 1.2k++ flow errors to address. 

However, if you insist, I can put other issues on hold and port the code base. I'm thinking this might take a week.

**Comment by bruce-binary** [comment]
I think... my big mistake was to upgrade ESLint. Big big mistake. Those "suggestions" I followed caused flow to break like crazy. I could have saved half a day of rather pointless work.

**Pull request merged**
